# 10 Academy: Artificial Intelligence Mastery
# Situational Overview 
# User Overview analysis

In [1]:
import sys
import os
import pandas as pd

# Add the scripts directory to the Python path
scripts_dir = r'E:\2017.Study\Tenx\Week-2\Situation_Overview\W2.Situation_Overview\scripts'
src_dir = r'E:\2017.Study\Tenx\Week-2\Situation_Overview\W2.Situation_Overview\src'
sys.path.append(scripts_dir)
sys.path.append(src_dir)
from connection import DatabaseConnector
from utils import DataUtils

# 1. Data Extraction 
# Connect to the database and pandas.

In [2]:
db_connector = DatabaseConnector()

# Connect to the database
db_connector.connect()

# Define and execute a query
query = "SELECT * FROM xdr_data;"
df = db_connector.execute_query(query)

# Print the DataFrame
if df is not None:
    print(df)
db_connector.close_connection()
print("Columns in DataFrame:", df.columns)

Connection successful.
           Bearer Id            Start  Start ms              End  End ms  \
0       1.311448e+19   4/4/2019 12:01     770.0  4/25/2019 14:35   662.0
1       1.311448e+19   4/9/2019 13:04     235.0   4/25/2019 8:15   606.0
2       1.311448e+19   4/9/2019 17:42       1.0  4/25/2019 11:58   652.0
3       1.311448e+19   4/10/2019 0:31     486.0   4/25/2019 7:36   171.0
4       1.311448e+19  4/12/2019 20:10     565.0  4/25/2019 10:40   954.0
...              ...              ...       ...              ...     ...
149996  7.277826e+18   4/29/2019 7:28     451.0   4/30/2019 6:02   214.0
149997  7.349883e+18   4/29/2019 7:28     483.0  4/30/2019 10:41   187.0
149998  1.311448e+19   4/29/2019 7:28     283.0  4/30/2019 10:46   810.0
149999  1.311448e+19   4/29/2019 7:28     696.0  4/30/2019 10:40   327.0
150000           NaN             None       NaN             None     NaN

        Dur. (ms)          IMSI  MSISDN/Number          IMEI  \
0       1823652.0  2.082014e+14   3.366496e+10  3.552121e+13
1       1365104.0  2.082019e+14   3.368185e+10  3.579401e+13
2       1361762.0  2.082003e+14   3.376063e+10  3.528151e+13
3       1321509.0  2.082014e+14   3.375034e+10  3.535661e+13
4       1089009.0  2.082014e+14   3.369980e+10  3.540701e+13
...           ...           ...            ...           ...
149996    81230.0  2.082022e+14   3.365069e+10  3.548311e+13
149997    97970.0  2.082019e+14   3.366345e+10  3.566051e+13
149998    98249.0  2.082017e+14   3.362189e+10  3.572121e+13
149999    97910.0  2.082021e+14   3.361962e+10  8.618620e+13
150000        NaN           NaN            NaN           NaN

           Last Location Name  ...  Youtube DL (Bytes)  Youtube UL (Bytes)  \
0       9.16456699548519E+015  ...        1.585461e+07        2.501332e+06
1                     L77566A  ...        2.024740e+07        1.911173e+07
2                     D42335A  ...        1.972566e+07        1.469958e+07
3                     T21824A  ...        2.138812e+07        1.514664e+07
4                     D88865A  ...        1.525938e+07        1.896287e+07
...                       ...  ...                 ...                 ...
149996                D20434A  ...        1.619167e+07        1.176343e+07
149997                D10223C  ...        1.387723e+07        8.288284e+06
149998                T51102A  ...        2.266051e+07        1.855903e+06
149999                L88342B  ...        8.817106e+06        8.305402e+06
150000                   None  ...        1.163407e+07        1.100941e+07

        Netflix DL (Bytes)  Netflix UL (Bytes)  Gaming DL (Bytes)  \
0             8.198936e+06        9.656251e+06       2.780823e+08
1             1.833841e+07        1.722713e+07       6.087501e+08
2             1.758779e+07        6.163408e+06       2.295846e+08
3             1.399465e+07        1.097942e+06       7.995382e+08
4             1.712458e+07        4.152180e+05       5.277072e+08
...                    ...                 ...                ...
149996        1.788370e+07        1.967816e+07       5.266097e+08
149997        1.935015e+07        2.129315e+07       6.268931e+08
149998        9.963942e+06        5.065760e+06       5.535395e+08
149999        3.322253e+06        1.317259e+07       3.525370e+08
150000        1.162685e+07        1.100175e+07       4.220447e+08

        Gaming UL (Bytes)  Other DL (Bytes)  Other UL (Bytes)  \
0            1.434415e+07      1.717444e+08      8.814393e+06
1            1.170709e+06      5.269042e+08      1.505514e+07
2            3.956300e+05      4.106926e+08      4.215763e+06
3            1.084972e+07      7.490399e+08      1.279728e+07
4            3.529801e+06      5.507095e+08      1.391032e+07
...                   ...               ...               ...
149996       9.197207e+06      3.264510e+06      1.348742e+07
149997       4.735033e+06      7.121804e+08      2.457758e+06
149998       1.339432e+07      1.211009e+08      1.131473e+07
149999       2.529475e+06      8.147131e+08      1.406930e+06
150000       8.288398e+06      4.211005e+08      8.264799e+06

        Total UL (Bytes)  Total DL (Bytes)
0             36749741.0       308879636.0
1             53800391.0       653384965.0
2             27883638.0       279807335.0
3             43324218.0       846028530.0
4             38542814.0       569138589.0
...                  ...               ...
149996        57628851.0       574175259.0
149997        39135081.0       666648844.0
149998        34912224.0       592786405.0
149999        29626096.0       371895920.0
150000               NaN               NaN

[150001 rows x 55 columns]
Connection closed.
Columns in DataFrame: Index(['Bearer Id', 'Start', 'Start ms', 'End', 'End ms', 'Dur. (ms)', 'IMSI',
       'MSISDN/Number', 'IMEI', 'Last Location Name', 'Avg RTT DL (ms)',
       'Avg RTT UL (ms)', 'Avg Bearer TP DL (kbps)', 'Avg Bearer TP UL (kbps)',
       'TCP DL Retrans. Vol (Bytes)', 'TCP UL Retrans. Vol (Bytes)',
       'DL TP < 50 Kbps (%)', '50 Kbps < DL TP < 250 Kbps (%)',
       '250 Kbps < DL TP < 1 Mbps (%)', 'DL TP > 1 Mbps (%)',
       'UL TP < 10 Kbps (%)', '10 Kbps < UL TP < 50 Kbps (%)',
       '50 Kbps < UL TP < 300 Kbps (%)', 'UL TP > 300 Kbps (%)',
       'HTTP DL (Bytes)', 'HTTP UL (Bytes)', 'Activity Duration DL (ms)',
       'Activity Duration UL (ms)', 'Dur. (ms).1', 'Handset Manufacturer',
       'Handset Type', 'Nb of sec with 125000B < Vol DL',
       'Nb of sec with 1250B < Vol UL < 6250B',
       'Nb of sec with 31250B < Vol DL < 125000B',
       'Nb of sec with 37500B < Vol UL',
       'Nb of sec with 6250B < Vol DL < 31250B',
       'Nb of sec with 6250B < Vol UL < 37500B',
       'Nb of sec with Vol DL < 6250B', 'Nb of sec with Vol UL < 1250B',
       'Social Media DL (Bytes)', 'Social Media UL (Bytes)',
       'Google DL (Bytes)', 'Google UL (Bytes)', 'Email DL (Bytes)',
       'Email UL (Bytes)', 'Youtube DL (Bytes)', 'Youtube UL (Bytes)',
       'Netflix DL (Bytes)', 'Netflix UL (Bytes)', 'Gaming DL (Bytes)',
       'Gaming UL (Bytes)', 'Other DL (Bytes)', 'Other UL (Bytes)',
       'Total UL (Bytes)', 'Total DL (Bytes)'],
      dtype='object')

# 2. Data Cleansing 
# Missing Value, Outliers, and data conversion

In [3]:
data_utils = DataUtils(df)
missing_summary = data_utils.check_missing_values()
print("Missing Values Summary:\n", missing_summary)

Total columns with missing values: 41
Top 5 columns with the most missing values:
                                          Missing Values Percentage    Dtype
Nb of sec with 37500B < Vol UL                    130254      86.8%  float64
Nb of sec with 6250B < Vol UL < 37500B            111843      74.6%  float64
Nb of sec with 125000B < Vol DL                    97538      65.0%  float64
TCP UL Retrans. Vol (Bytes)                        96649      64.4%  float64
Nb of sec with 31250B < Vol DL < 125000B           93586      62.4%  float64
Missing Values Summary:
                                           Missing Values Percentage    Dtype
Nb of sec with 37500B < Vol UL                    130254      86.8%  float64
Nb of sec with 6250B < Vol UL < 37500B            111843      74.6%  float64
Nb of sec with 125000B < Vol DL                    97538      65.0%  float64
TCP UL Retrans. Vol (Bytes)                        96649      64.4%  float64
Nb of sec with 31250B < Vol DL < 125000B           93586      62.4%  float64
Nb of sec with 1250B < Vol UL < 6250B              92894      61.9%  float64
Nb of sec with 6250B < Vol DL < 31250B             88317      58.9%  float64
TCP DL Retrans. Vol (Bytes)                        88146      58.8%  float64
HTTP UL (Bytes)                                    81810      54.5%  float64
HTTP DL (Bytes)                                    81474      54.3%  float64
Avg RTT DL (ms)                                    27829      18.6%  float64
Avg RTT UL (ms)                                    27812      18.5%  float64
Last Location Name                                  1153       0.8%   object
Bearer Id                                            991       0.7%  float64
MSISDN/Number                                       1066       0.7%  float64
10 Kbps < UL TP < 50 Kbps (%)                        792       0.5%  float64
Nb of sec with Vol DL < 6250B                        755       0.5%  float64
Nb of sec with Vol UL < 1250B                        793       0.5%  float64
UL TP > 300 Kbps (%)                                 792       0.5%  float64
50 Kbps < UL TP < 300 Kbps (%)                       792       0.5%  float64
UL TP < 10 Kbps (%)                                  792       0.5%  float64
250 Kbps < DL TP < 1 Mbps (%)                        754       0.5%  float64
50 Kbps < DL TP < 250 Kbps (%)                       754       0.5%  float64
DL TP < 50 Kbps (%)                                  754       0.5%  float64
DL TP > 1 Mbps (%)                                   754       0.5%  float64
Handset Manufacturer                                 572       0.4%   object
Handset Type                                         572       0.4%   object
IMEI                                                 572       0.4%  float64
IMSI                                                 570       0.4%  float64
Start                                                  1       0.0%   object
Dur. (ms)                                              1       0.0%  float64
Total UL (Bytes)                                       1       0.0%  float64
Start ms                                               1       0.0%  float64
End                                                    1       0.0%   object
End ms                                                 1       0.0%  float64
Avg Bearer TP UL (kbps)                                1       0.0%  float64
Avg Bearer TP DL (kbps)                                1       0.0%  float64
Dur. (ms).1                                            1       0.0%  float64
Activity Duration UL (ms)                              1       0.0%  float64
Activity Duration DL (ms)                              1       0.0%  float64
Total DL (Bytes)                                       1       0.0%  float64

Columns with more than 50% missing data frequently offer incomplete information, which, if imputed, might distort the analysis and add noise. High missingness might be a sign of issues with data collection, and dealing with such columns can make analysis more difficult without bringing much benefit. These columns can be eliminated so that more comprehensive and trustworthy data can be examined, which would increase statistical efficiency and provide clearer, more accurate insights.

For investors, this means decisions based on such incomplete or unreliable data may lead to suboptimal investment choices or missed opportunities.

Investment Risk: Relying on datasets with substantial missing values can introduce uncertainty and increase investment risk. Investors might end up underestimating potential risks or overvaluing opportunities due to gaps in the data.

# Handling Missing Value 
handles skewness in the handle_missing_values method, where it decides whether to fill missing values with the median or mean based on the skewness of the distribution of the numeric columns.

In [6]:
df = data_utils.handle_missing_values()
df.head()

Missing values handled and high missing value columns dropped.

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

# Outliers , Fix( Median, Mean) and Remove Based on Z Score

In [11]:

outliers = data_utils.detect_outliers()

for column, outlier_indices in outliers.items():
    print(f"Outliers in column '{column}': {outlier_indices[:5]}")  # Show first 5 outlier indices

df = data_utils.fix_outliers()
df = data_utils.remove_outliers()
df.head()

Outlier detection complete.
Outliers in column 'Bearer Id': Index([], dtype='int64')
Outliers in column 'Start ms': Index([], dtype='int64')
Outliers in column 'End ms': Index([], dtype='int64')
Outliers in column 'Dur. (ms)': Index([], dtype='int64')
Outliers in column 'IMSI': Index([], dtype='int64')
Outliers in column 'MSISDN/Number': Index([], dtype='int64')
Outliers in column 'IMEI': Index([], dtype='int64')
Outliers in column 'Avg RTT DL (ms)': Index([], dtype='int64')
Outliers in column 'Avg RTT UL (ms)': Index([], dtype='int64')
Outliers in column 'Avg Bearer TP DL (kbps)': Index([3245, 4952, 5105, 5426, 5583], dtype='int64')
Outliers in column 'Avg Bearer TP UL (kbps)': Index([13, 127, 149, 364, 618], dtype='int64')
Outliers in column 'TCP DL Retrans. Vol (Bytes)': Index([13809, 20689, 88458], dtype='int64')
Outliers in column 'TCP UL Retrans. Vol (Bytes)': Index([81508, 89368, 139609], dtype='int64')
Outliers in column 'DL TP < 50 Kbps (%)': Index([], dtype='int64')
Outliers in column '50 Kbps < DL TP < 250 Kbps (%)': Index([], dtype='int64')
Outliers in column '250 Kbps < DL TP < 1 Mbps (%)': Index([], dtype='int64')
Outliers in column 'DL TP > 1 Mbps (%)': Index([], dtype='int64')
Outliers in column 'UL TP < 10 Kbps (%)': Index([], dtype='int64')
Outliers in column '10 Kbps < UL TP < 50 Kbps (%)': Index([], dtype='int64')
Outliers in column '50 Kbps < UL TP < 300 Kbps (%)': Index([], dtype='int64')
Outliers in column 'UL TP > 300 Kbps (%)': Index([], dtype='int64')
Outliers in column 'HTTP DL (Bytes)': Index([88703, 89368, 90779], dtype='int64')
Outliers in column 'HTTP UL (Bytes)': Index([49187, 76474, 88703, 89368, 90779], dtype='int64')
Outliers in column 'Activity Duration DL (ms)': Index([22388, 25104, 25672, 25716, 25873], dtype='int64')
Outliers in column 'Activity Duration UL (ms)': Index([31, 54, 65, 79, 103], dtype='int64')
Outliers in column 'Dur. (ms).1': Index([], dtype='int64')
Outliers in column 'Nb of sec with 125000B < Vol DL': Index([], dtype='int64')
Outliers in column 'Nb of sec with 1250B < Vol UL < 6250B': Index([], dtype='int64')
Outliers in column 'Nb of sec with 31250B < Vol DL < 125000B': Index([], dtype='int64')
Outliers in column 'Nb of sec with 37500B < Vol UL': Index([], dtype='int64')
Outliers in column 'Nb of sec with 6250B < Vol DL < 31250B': Index([], dtype='int64')
Outliers in column 'Nb of sec with 6250B < Vol UL < 37500B': Index([], dtype='int64')
Outliers in column 'Nb of sec with Vol DL < 6250B': Index([37, 45, 59, 4435, 7159], dtype='int64')
Outliers in column 'Nb of sec with Vol UL < 1250B': Index([65, 89, 102, 489, 21784], dtype='int64')
Outliers in column 'Social Media DL (Bytes)': Index([], dtype='int64')
Outliers in column 'Social Media UL (Bytes)': Index([], dtype='int64')
Outliers in column 'Google DL (Bytes)': Index([], dtype='int64')
Outliers in column 'Google UL (Bytes)': Index([], dtype='int64')
Outliers in column 'Email DL (Bytes)': Index([], dtype='int64')
Outliers in column 'Email UL (Bytes)': Index([], dtype='int64')
Outliers in column 'Youtube DL (Bytes)': Index([], dtype='int64')
Outliers in column 'Youtube UL (Bytes)': Index([], dtype='int64')
Outliers in column 'Netflix DL (Bytes)': Index([], dtype='int64')
Outliers in column 'Netflix UL (Bytes)': Index([], dtype='int64')
Outliers in column 'Gaming DL (Bytes)': Index([], dtype='int64')
Outliers in column 'Gaming UL (Bytes)': Index([], dtype='int64')
Outliers in column 'Other DL (Bytes)': Index([], dtype='int64')
Outliers in column 'Other UL (Bytes)': Index([], dtype='int64')
Outliers in column 'Total UL (Bytes)': Index([21678, 27926, 31704, 31817, 35056], dtype='int64')
Outliers in column 'Total DL (Bytes)': Index([], dtype='int64')
Outliers removed.

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,86399.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,8291208.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,86399.0,2.082015e+14,3.368185e+10,3.579401e+13,L77566A,...,11602467.0,11013447.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,8266788.0,41138698.5,653384965.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,86399.0,2.082014e+14,3.366295e+10,3.535661e+13,T21824A,...,11602467.0,15146643.0,13994646.0,1097942.0,423408104.0,10849722.0,420378288.0,12797283.0,43324218.0,455841077.5
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,500.0,86399.0,2.082014e+14,3.366295e+10,3.540701e+13,D88865A,...,15259380.0,11013447.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,8266788.0,38542814.0,569138589.0
5,1.311448e+19,4/12/2019 21:37,439.0,4/25/2019 8:08,553.0,86399.0,2.082014e+14,3.366819e+10,3.529841e+13,T89132C,...,11602467.0,2611113.0,7345361.0,6536448.0,423408104.0,13167974.0,654978277.0,4436057.0,30307754.0,455841077.5

# Data Conversion  
Converting columns with bytes to megabytes 
This is done by reading columns titled "(Bytes)"

In [12]:
df = data_utils.convert_bytes_to_megabytes()

Converted byte columns to megabytes.

# 2. User Overview Analysis